# Generated by Django 5.1.7 on 2025-03-26 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='users',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
