# Generated by Django 5.1.7 on 2025-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0002_remove_roombooking_user_roombooking_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
