# Generated by Django 5.1.6 on 2025-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0003_roombooking_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='James Graham', max_length=255),
        ),
    ]
