# Generated by Django 5.1.6 on 2025-03-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read_status',
            new_name='is_read',
        ),
    ]
